<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Do not edit by hand: the next generation replaces this file. Changes belong in the
 * API description or in the generator.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Validation;

use Prefabcortex\DhlParcelDeShippingV2\Exception\ApiException;
use RuntimeException;
use Symfony\Component\Validator\ConstraintViolationListInterface;

use function sprintf;

/**
 * A document that does not satisfy the constraints its schema declares — out of an operation, a
 * request body checked before it is sent.
 *
 * Carries {@see ApiException} because it leaves an operation on the same path and in the same
 * `@throws` list as the operation exceptions beside it. Without the marker the one catch the README
 * documents let it through.
 *
 * It carries no response accessors and so is not a `ResponseException`: where it is raised there is
 * no response. A *response* that breaks its constraints used to raise this too, and so looked
 * exactly like a request that never left — while the request had arrived and done what it asked
 * for. That case is `ResponseValidationException` now, a sibling rather than a subclass on purpose:
 * a catch of this class must keep meaning "nothing was sent".
 */
final class ValidationException extends RuntimeException implements ApiException
{
    public function __construct(private readonly ConstraintViolationListInterface $violationList)
    {
        parent::__construct(sprintf('Model validation failed with %d errors.', $violationList->count()), 400);
    }

    public function getViolationList(): ConstraintViolationListInterface
    {
        return $this->violationList;
    }
}
