<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Do not edit by hand: the next generation replaces this file. Changes belong in the
 * API description or in the generator.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Authentication;

use Psr\Http\Message\RequestInterface;

use function array_diff;
use function array_map;
use function in_array;

/**
 * The authenticators a client was built with, and the rule for choosing among them.
 *
 * An operation states its security requirements as alternatives: a list of scheme-name sets, any
 * one of which is sufficient. This applies the first alternative whose schemes are all covered by
 * a registered authenticator, which is what "OR between entries, AND within one" means in an
 * OpenAPI `security` block. A request whose requirements none of the registered authenticators
 * satisfy goes out unsigned — the server, not the client, decides what that is worth.
 *
 * That last rule stays deliberately quiet, and it is worth saying why, because it once hid a real
 * defect: for a description requiring two schemes at once, no generated factory could register
 * both, so every client sent every request unsigned and only the server ever said so. The fix
 * belonged where the factories are written, not here. Throwing instead would break the case this
 * silence exists for — a description may name a scheme this package generates no authenticator for
 * (`openIdConnect`, `mutualTLS`), and its caller signs that part in their own PSR-18 client. From
 * inside here, "signed elsewhere" and "forgotten" look exactly alike.
 *
 * To register several schemes for one request, call the factory the client emits for that
 * requirement, or `Client::withAuthenticators()`.
 *
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
final readonly class AuthenticatorRegistry
{
    /** @param list<Authenticator> $authenticators */
    public function __construct(private array $authenticators)
    {
    }

    /** @param list<list<string>> $securityRequirements alternatives, each a set of scheme names */
    public function authenticate(RequestInterface $request, array $securityRequirements): RequestInterface
    {
        $registeredSchemes = array_map(static fn (Authenticator $authenticator): string => $authenticator->getSecuritySchemeName(), $this->authenticators);
        foreach ($securityRequirements as $requiredSchemes) {
            if ([] === array_diff($requiredSchemes, $registeredSchemes)) {
                foreach ($this->authenticators as $authenticator) {
                    if (in_array($authenticator->getSecuritySchemeName(), $requiredSchemes, true)) {
                        $request = $authenticator->authenticate($request);
                    }
                }

                return $request;
            }
        }

        return $request;
    }
}
