<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

/**
 * Builds a {@see BankAccount}.
 */
final class BankAccountBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $bankName
     * @param Option<string>           $bic
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $accountHolder,
        private string $iban,
        private Option $bankName,
        private Option $bic,
        private array $additionalProperties,
    ) {
    }

    public function setAccountHolder(string $accountHolder): self
    {
        $this->accountHolder = $accountHolder;

        return $this;
    }

    public function setIban(string $iban): self
    {
        $this->iban = $iban;

        return $this;
    }

    public function setBankName(string $bankName): self
    {
        $this->bankName = Some::create($bankName);

        return $this;
    }

    public function setBic(string $bic): self
    {
        $this->bic = Some::create($bic);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): BankAccount
    {
        return new BankAccount(
            $this->accountHolder,
            $this->iban,
            $this->bankName,
            $this->bic,
            $this->additionalProperties,
        );
    }
}
