<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

/**
 * Builds a {@see Dimensions}.
 */
final class DimensionsBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param DimensionsUom|UnknownEnumValue<string> $uom
     * @param array<int|string, mixed>               $additionalProperties
     */
    public function __construct(
        private DimensionsUom|UnknownEnumValue $uom,
        private int $height,
        private int $length,
        private int $width,
        private array $additionalProperties,
    ) {
    }

    /**
     * Unit of metric, applies to all dimensions contained.
     */
    public function setUom(DimensionsUom $uom): self
    {
        $this->uom = $uom;

        return $this;
    }

    public function setHeight(int $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function setLength(int $length): self
    {
        $this->length = $length;

        return $this;
    }

    public function setWidth(int $width): self
    {
        $this->width = $width;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Dimensions
    {
        return new Dimensions($this->uom, $this->height, $this->length, $this->width, $this->additionalProperties);
    }
}
