<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Exception\MalformedDataException;
use Prefabcortex\DhlParcelDeShippingV2\Optional\None;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class Document implements SelfNormalizingModel
{
    /**
     * @param Option<string>                                       $b64
     * @param Option<string>                                       $zpl2
     * @param Option<string>                                       $url
     * @param Option<DocumentFileFormat|UnknownEnumValue<string>>  $fileFormat
     * @param Option<DocumentPrintFormat|UnknownEnumValue<string>> $printFormat
     * @param array<int|string, mixed>                             $additionalProperties
     */
    public function __construct(
        private Option $b64,
        private Option $zpl2,
        private Option $url,
        private Option $fileFormat,
        private Option $printFormat,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): DocumentBuilder
    {
        return new DocumentBuilder(None::create(), None::create(), None::create(), None::create(), None::create(), []);
    }

    /**
     * The Base64 encoded byte stream.
     *
     * @return Option<string>
     */
    public function getB64(): Option
    {
        return $this->b64;
    }

    /**
     * The document in zpl encoding.
     *
     * @return Option<string>
     */
    public function getZpl2(): Option
    {
        return $this->zpl2;
    }

    /**
     * URL reference to download document.
     *
     * @return Option<string>
     */
    public function getUrl(): Option
    {
        return $this->url;
    }

    /**
     * format of the encoded bytes.
     *
     * @return Option<DocumentFileFormat|UnknownEnumValue<string>>
     */
    public function getFileFormat(): Option
    {
        return $this->fileFormat;
    }

    /**
     * The print format used. Customs documents and cash on delivery documents can only be returned
     * in format A4.
     *
     * @return Option<DocumentPrintFormat|UnknownEnumValue<string>>
     */
    public function getPrintFormat(): Option
    {
        return $this->printFormat;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $b64 = None::create();
        $zpl2 = None::create();
        $url = None::create();
        $fileFormat = None::create();
        $printFormat = None::create();
        if (array_key_exists('b64', $data) && $data['b64'] !== null) {
            $b64Raw = $data['b64'];
            if (!is_string($b64Raw)) {
                throw new MalformedDataException(
                    sprintf('Property "b64" must be string, got %s.', get_debug_type($b64Raw)),
                );
            }
            $b64 = Some::create($b64Raw);
        }
        if (array_key_exists('zpl2', $data) && $data['zpl2'] !== null) {
            $zpl2Raw = $data['zpl2'];
            if (!is_string($zpl2Raw)) {
                throw new MalformedDataException(
                    sprintf('Property "zpl2" must be string, got %s.', get_debug_type($zpl2Raw)),
                );
            }
            $zpl2 = Some::create($zpl2Raw);
        }
        if (array_key_exists('url', $data) && $data['url'] !== null) {
            $urlRaw = $data['url'];
            if (!is_string($urlRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "url" must be string, got %s.', get_debug_type($urlRaw)),
                );
            }
            $url = Some::create($urlRaw);
        }
        if (array_key_exists('fileFormat', $data) && $data['fileFormat'] !== null) {
            $fileFormatRaw = $data['fileFormat'];
            if (!is_string($fileFormatRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "fileFormat" must be string, got %s.', get_debug_type($fileFormatRaw)),
                );
            }
            $fileFormat = Some::create(
                DocumentFileFormat::tryFrom($fileFormatRaw) ?? UnknownEnumValue::of($fileFormatRaw),
            );
        }
        if (array_key_exists('printFormat', $data) && $data['printFormat'] !== null) {
            $printFormatRaw = $data['printFormat'];
            if (!is_string($printFormatRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "printFormat" must be string, got %s.', get_debug_type($printFormatRaw)),
                );
            }
            $printFormat = Some::create(
                DocumentPrintFormat::tryFrom($printFormatRaw) ?? UnknownEnumValue::of($printFormatRaw),
            );
        }
        $additionalProperties = array_diff_key(
            $data,
            ['b64' => true, 'zpl2' => true, 'url' => true, 'fileFormat' => true, 'printFormat' => true],
        );

        return new self($b64, $zpl2, $url, $fileFormat, $printFormat, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $b64Option = $this->b64;
        if ($b64Option->isDefined()) {
            $b64 = $b64Option->get();
            $dataArray['b64'] = $b64;
        }
        $zpl2Option = $this->zpl2;
        if ($zpl2Option->isDefined()) {
            $zpl2 = $zpl2Option->get();
            $dataArray['zpl2'] = $zpl2;
        }
        $urlOption = $this->url;
        if ($urlOption->isDefined()) {
            $url = $urlOption->get();
            $dataArray['url'] = $url;
        }
        $fileFormatOption = $this->fileFormat;
        if ($fileFormatOption->isDefined()) {
            $fileFormat = $fileFormatOption->get();
            $dataArray['fileFormat'] = $fileFormat->value;
        }
        $printFormatOption = $this->printFormat;
        if ($printFormatOption->isDefined()) {
            $printFormat = $printFormatOption->get();
            $dataArray['printFormat'] = $printFormat->value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): DocumentBuilder
    {
        return new DocumentBuilder(
            $this->b64,
            $this->zpl2,
            $this->url,
            $this->fileFormat,
            $this->printFormat,
            $this->additionalProperties,
        );
    }
}
