<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

/**
 * Builds a {@see Document}.
 */
final class DocumentBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                                       $b64
     * @param Option<string>                                       $zpl2
     * @param Option<string>                                       $url
     * @param Option<DocumentFileFormat|UnknownEnumValue<string>>  $fileFormat
     * @param Option<DocumentPrintFormat|UnknownEnumValue<string>> $printFormat
     * @param array<int|string, mixed>                             $additionalProperties
     */
    public function __construct(
        private Option $b64,
        private Option $zpl2,
        private Option $url,
        private Option $fileFormat,
        private Option $printFormat,
        private array $additionalProperties,
    ) {
    }

    /**
     * The Base64 encoded byte stream.
     */
    public function setB64(string $b64): self
    {
        $this->b64 = Some::create($b64);

        return $this;
    }

    /**
     * The document in zpl encoding.
     */
    public function setZpl2(string $zpl2): self
    {
        $this->zpl2 = Some::create($zpl2);

        return $this;
    }

    /**
     * URL reference to download document.
     */
    public function setUrl(string $url): self
    {
        $this->url = Some::create($url);

        return $this;
    }

    /**
     * format of the encoded bytes.
     */
    public function setFileFormat(DocumentFileFormat $fileFormat): self
    {
        $this->fileFormat = Some::create($fileFormat);

        return $this;
    }

    /**
     * The print format used. Customs documents and cash on delivery documents can only be returned
     * in format A4.
     */
    public function setPrintFormat(DocumentPrintFormat $printFormat): self
    {
        $this->printFormat = Some::create($printFormat);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Document
    {
        return new Document(
            $this->b64,
            $this->zpl2,
            $this->url,
            $this->fileFormat,
            $this->printFormat,
            $this->additionalProperties,
        );
    }
}
