<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Exception\MalformedDataException;
use Prefabcortex\DhlParcelDeShippingV2\Optional\None;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class LabelDataResponse implements SelfNormalizingModel
{
    /**
     * @param Option<RequestStatus>      $status
     * @param Option<list<ResponseItem>> $items
     * @param array<int|string, mixed>   $additionalProperties
     */
    public function __construct(private Option $status, private Option $items, private array $additionalProperties)
    {
    }

    public static function builder(): LabelDataResponseBuilder
    {
        return new LabelDataResponseBuilder(None::create(), None::create(), []);
    }

    /**
     * General status description for the attached response or response item.
     *
     * @return Option<RequestStatus>
     */
    public function getStatus(): Option
    {
        return $this->status;
    }

    /**
     * If the request contains a multi element array (e.g. multiple shipments), then the order of
     * the items in the response corresponds to the order of the items in the request. For
     * consistency, if the request contains only one item then the response contains a single
     * element array.
     *
     * @return Option<list<ResponseItem>>
     */
    public function getItems(): Option
    {
        return $this->items;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $status = None::create();
        $items = None::create();
        if (array_key_exists('status', $data) && $data['status'] !== null) {
            $statusRaw = $data['status'];
            if (!is_array($statusRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "status" must be object, got %s.', get_debug_type($statusRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $statusRawTyped */
            $statusRawTyped = $statusRaw;
            $status = Some::create(RequestStatus::fromArray($statusRawTyped));
        }
        if (array_key_exists('items', $data) && $data['items'] !== null) {
            $itemsRaw = $data['items'];
            if (!(is_array($itemsRaw) && array_is_list($itemsRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "items" must be list, got %s.', get_debug_type($itemsRaw)),
                );
            }
            $items = Some::create(array_map(static function (mixed $value): ResponseItem {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var non-empty-array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return ResponseItem::fromArray($valueTyped);
            }, $itemsRaw));
        }
        $additionalProperties = array_diff_key($data, ['status' => true, 'items' => true]);

        return new self($status, $items, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $statusOption = $this->status;
        if ($statusOption->isDefined()) {
            $status = $statusOption->get();
            $dataArray['status'] = $normalizationTarget->model($status);
        }
        $itemsOption = $this->items;
        if ($itemsOption->isDefined()) {
            $items = $itemsOption->get();
            $values = [];
            foreach ($items as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['items'] = $values;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): LabelDataResponseBuilder
    {
        return new LabelDataResponseBuilder($this->status, $this->items, $this->additionalProperties);
    }
}
