<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

/**
 * Builds a {@see Locker}.
 */
final class LockerBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<Country|UnknownEnumValue<string>> $country
     * @param array<int|string, mixed>                 $additionalProperties
     */
    public function __construct(
        private string $name,
        private int $lockerID,
        private string $postNumber,
        private string $city,
        private string $postalCode,
        private Option $country,
        private array $additionalProperties,
    ) {
    }

    /**
     * Name.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Packstationnummer. Three digit number identifying the parcel locker in conjunction with city
     * and postal code.
     */
    public function setLockerID(int $lockerID): self
    {
        $this->lockerID = $lockerID;

        return $this;
    }

    /**
     * postNumber (Postnummer) is the official account number a private DHL Customer gets upon
     * registration.
     */
    public function setPostNumber(string $postNumber): self
    {
        $this->postNumber = $postNumber;

        return $this;
    }

    /**
     * City where the locker is located.
     */
    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    /**
     * A valid country code consisting of three characters according to ISO 3166-1 alpha-3.
     */
    public function setCountry(Country $country): self
    {
        $this->country = Some::create($country);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Locker
    {
        return new Locker(
            $this->name,
            $this->lockerID,
            $this->postNumber,
            $this->city,
            $this->postalCode,
            $this->country,
            $this->additionalProperties,
        );
    }
}
