<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

/**
 * Builds a {@see MultipleManifestResponse}.
 */
final class MultipleManifestResponseBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<RequestStatus>           $status
     * @param Option<list<ShortResponseItem>> $items
     * @param array<int|string, mixed>        $additionalProperties
     */
    public function __construct(private Option $status, private Option $items, private array $additionalProperties)
    {
    }

    /**
     * General status description for the attached response or response item.
     */
    public function setStatus(RequestStatus $status): self
    {
        $this->status = Some::create($status);

        return $this;
    }

    /** @param list<ShortResponseItem> $items */
    public function setItems(array $items): self
    {
        $this->items = Some::create($items);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): MultipleManifestResponse
    {
        return new MultipleManifestResponse($this->status, $this->items, $this->additionalProperties);
    }
}
