<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Do not edit by hand: the next generation replaces this file. Changes belong in the
 * API description or in the generator.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

/**
 * What a model is normalized into: a PHP array, or a JSON document.
 *
 * The two differ in one place only — a JSON object that happens to be empty. PHP has one array for
 * both lists and dictionaries, and `json_encode([])` writes `[]`: a model none of whose properties
 * was set, or a map with no entries, went out as an empty *array* where the description asks for an
 * object, and a server checking types rejects it. A `stdClass` encodes as `{}`, empty or not.
 *
 * Every other value is the same either way, so each generated model has a single `normalize()`
 * body, and the positions that hold an object ask this which form to write. `toArray()` keeps
 * answering the plain array that `fromArray()` reads back and the validator checks;
 * `jsonSerialize()` answers the JSON document.
 */
enum NormalizationTarget
{
    case PhpArray;
    case Json;

    /**
     * A nested model, in this target's form.
     *
     * @return array<int|string, mixed>|object
     */
    public function model(SelfNormalizingModel $model): array|object
    {
        return match ($this) {
            self::PhpArray => $model->toArray(),
            self::Json => $model->jsonSerialize(),
        };
    }

    /**
     * A JSON object held as a PHP array — a map, `additionalProperties`, a free-form object — in
     * this target's form.
     *
     * The cast is also what keeps a map with numeric keys an object: `['0' => 'a']` is the list
     * `["a"]` to `json_encode()`, but `{"0":"a"}` once it is a `stdClass`.
     *
     * @param array<int|string, mixed> $map
     *
     * @return array<int|string, mixed>|object
     */
    public function map(array $map): array|object
    {
        return match ($this) {
            self::PhpArray => $map,
            self::Json => (object) $map,
        };
    }
}
