<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Exception\MalformedDataException;
use Prefabcortex\DhlParcelDeShippingV2\Optional\None;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_int;
use function is_string;
use function sprintf;

final readonly class POBox implements SelfNormalizingModel
{
    /**
     * @param Option<string>                           $name2
     * @param Option<string>                           $name3
     * @param Option<string>                           $email
     * @param Option<Country|UnknownEnumValue<string>> $country
     * @param array<int|string, mixed>                 $additionalProperties
     */
    public function __construct(
        private string $name1,
        private int $poBoxID,
        private string $city,
        private string $postalCode,
        private Option $name2,
        private Option $name3,
        private Option $email,
        private Option $country,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $name1, int $poBoxID, string $city, string $postalCode): POBoxBuilder
    {
        return new POBoxBuilder(
            $name1,
            $poBoxID,
            $city,
            $postalCode,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Name1. Line 1 of name information.
     */
    public function getName1(): string
    {
        return $this->name1;
    }

    /**
     * An optional, additional line of name information.
     *
     * @return Option<string>
     */
    public function getName2(): Option
    {
        return $this->name2;
    }

    /**
     * An optional, additional line of name information.
     *
     * @return Option<string>
     */
    public function getName3(): Option
    {
        return $this->name3;
    }

    /**
     * Number of P.O. Box (Postfach).
     */
    public function getPoBoxID(): int
    {
        return $this->poBoxID;
    }

    /**
     * Email address of the consignee.
     *
     * @return Option<string>
     */
    public function getEmail(): Option
    {
        return $this->email;
    }

    /**
     * City of the P.O. Box (Postfach) location.
     */
    public function getCity(): string
    {
        return $this->city;
    }

    /**
     * A valid country code consisting of three characters according to ISO 3166-1 alpha-3.
     *
     * @return Option<Country|UnknownEnumValue<string>>
     */
    public function getCountry(): Option
    {
        return $this->country;
    }

    /**
     * Postal code of the P.O. Box (Postfach) location.
     */
    public function getPostalCode(): string
    {
        return $this->postalCode;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $name1 = null;
        $name2 = None::create();
        $name3 = None::create();
        $poBoxID = null;
        $email = None::create();
        $city = null;
        $country = None::create();
        $postalCode = null;
        if (array_key_exists('name1', $data)) {
            $name1Raw = $data['name1'];
            if (!is_string($name1Raw)) {
                throw new MalformedDataException(
                    sprintf('Property "name1" must be string, got %s.', get_debug_type($name1Raw)),
                );
            }
            $name1 = $name1Raw;
        }
        if (array_key_exists('name2', $data) && $data['name2'] !== null) {
            $name2Raw = $data['name2'];
            if (!is_string($name2Raw)) {
                throw new MalformedDataException(
                    sprintf('Property "name2" must be string, got %s.', get_debug_type($name2Raw)),
                );
            }
            $name2 = Some::create($name2Raw);
        }
        if (array_key_exists('name3', $data) && $data['name3'] !== null) {
            $name3Raw = $data['name3'];
            if (!is_string($name3Raw)) {
                throw new MalformedDataException(
                    sprintf('Property "name3" must be string, got %s.', get_debug_type($name3Raw)),
                );
            }
            $name3 = Some::create($name3Raw);
        }
        if (array_key_exists('poBoxID', $data)) {
            $poBoxIDRaw = $data['poBoxID'];
            if (!is_int($poBoxIDRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "poBoxID" must be int, got %s.', get_debug_type($poBoxIDRaw)),
                );
            }
            $poBoxID = $poBoxIDRaw;
        }
        if (array_key_exists('email', $data) && $data['email'] !== null) {
            $emailRaw = $data['email'];
            if (!is_string($emailRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "email" must be string, got %s.', get_debug_type($emailRaw)),
                );
            }
            $email = Some::create($emailRaw);
        }
        if (array_key_exists('city', $data)) {
            $cityRaw = $data['city'];
            if (!is_string($cityRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "city" must be string, got %s.', get_debug_type($cityRaw)),
                );
            }
            $city = $cityRaw;
        }
        if (array_key_exists('country', $data) && $data['country'] !== null) {
            $countryRaw = $data['country'];
            if (!is_string($countryRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "country" must be string, got %s.', get_debug_type($countryRaw)),
                );
            }
            $country = Some::create(Country::tryFrom($countryRaw) ?? UnknownEnumValue::of($countryRaw));
        }
        if (array_key_exists('postalCode', $data)) {
            $postalCodeRaw = $data['postalCode'];
            if (!is_string($postalCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "postalCode" must be string, got %s.', get_debug_type($postalCodeRaw)),
                );
            }
            $postalCode = $postalCodeRaw;
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'name1' => true,
                'name2' => true,
                'name3' => true,
                'poBoxID' => true,
                'email' => true,
                'city' => true,
                'country' => true,
                'postalCode' => true,
            ],
        );
        if ($name1 === null) {
            throw new MalformedDataException('Required property "name1" is missing from the document.');
        }
        if ($poBoxID === null) {
            throw new MalformedDataException('Required property "poBoxID" is missing from the document.');
        }
        if ($city === null) {
            throw new MalformedDataException('Required property "city" is missing from the document.');
        }
        if ($postalCode === null) {
            throw new MalformedDataException('Required property "postalCode" is missing from the document.');
        }

        return new self($name1, $poBoxID, $city, $postalCode, $name2, $name3, $email, $country, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['name1'] = $this->name1;
        $name2Option = $this->name2;
        if ($name2Option->isDefined()) {
            $name2 = $name2Option->get();
            $dataArray['name2'] = $name2;
        }
        $name3Option = $this->name3;
        if ($name3Option->isDefined()) {
            $name3 = $name3Option->get();
            $dataArray['name3'] = $name3;
        }
        $dataArray['poBoxID'] = $this->poBoxID;
        $emailOption = $this->email;
        if ($emailOption->isDefined()) {
            $email = $emailOption->get();
            $dataArray['email'] = $email;
        }
        $dataArray['city'] = $this->city;
        $countryOption = $this->country;
        if ($countryOption->isDefined()) {
            $country = $countryOption->get();
            $dataArray['country'] = $country->value;
        }
        $dataArray['postalCode'] = $this->postalCode;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): POBoxBuilder
    {
        return new POBoxBuilder(
            $this->name1,
            $this->poBoxID,
            $this->city,
            $this->postalCode,
            $this->name2,
            $this->name3,
            $this->email,
            $this->country,
            $this->additionalProperties,
        );
    }
}
