<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

/**
 * Builds a {@see ServiceInformationAmp}.
 */
final class ServiceInformationAmpBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $name
     * @param Option<string>           $env
     * @param Option<string>           $version
     * @param Option<string>           $rev
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $name,
        private Option $env,
        private Option $version,
        private Option $rev,
        private array $additionalProperties,
    ) {
    }

    /**
     * name of api.
     */
    public function setName(string $name): self
    {
        $this->name = Some::create($name);

        return $this;
    }

    /**
     * environment.
     */
    public function setEnv(string $env): self
    {
        $this->env = Some::create($env);

        return $this;
    }

    /**
     * version of api.
     */
    public function setVersion(string $version): self
    {
        $this->version = Some::create($version);

        return $this;
    }

    /**
     * revision.
     */
    public function setRev(string $rev): self
    {
        $this->rev = Some::create($rev);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ServiceInformationAmp
    {
        return new ServiceInformationAmp(
            $this->name,
            $this->env,
            $this->version,
            $this->rev,
            $this->additionalProperties,
        );
    }
}
