<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Exception\MalformedDataException;
use Prefabcortex\DhlParcelDeShippingV2\Optional\None;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class ServiceInformation implements SelfNormalizingModel
{
    /**
     * @param Option<ServiceInformationAmp>     $amp
     * @param Option<ServiceInformationBackend> $backend
     * @param array<int|string, mixed>          $additionalProperties
     */
    public function __construct(private Option $amp, private Option $backend, private array $additionalProperties)
    {
    }

    public static function builder(): ServiceInformationBuilder
    {
        return new ServiceInformationBuilder(None::create(), None::create(), []);
    }

    /** @return Option<ServiceInformationAmp> */
    public function getAmp(): Option
    {
        return $this->amp;
    }

    /** @return Option<ServiceInformationBackend> */
    public function getBackend(): Option
    {
        return $this->backend;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $amp = None::create();
        $backend = None::create();
        if (array_key_exists('amp', $data) && $data['amp'] !== null) {
            $ampRaw = $data['amp'];
            if (!is_array($ampRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "amp" must be object, got %s.', get_debug_type($ampRaw)),
                );
            }
            /** @var array<string, mixed> $ampRawTyped */
            $ampRawTyped = $ampRaw;
            $amp = Some::create(ServiceInformationAmp::fromArray($ampRawTyped));
        }
        if (array_key_exists('backend', $data) && $data['backend'] !== null) {
            $backendRaw = $data['backend'];
            if (!is_array($backendRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "backend" must be object, got %s.', get_debug_type($backendRaw)),
                );
            }
            /** @var array<string, mixed> $backendRawTyped */
            $backendRawTyped = $backendRaw;
            $backend = Some::create(ServiceInformationBackend::fromArray($backendRawTyped));
        }
        $additionalProperties = array_diff_key($data, ['amp' => true, 'backend' => true]);

        return new self($amp, $backend, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $ampOption = $this->amp;
        if ($ampOption->isDefined()) {
            $amp = $ampOption->get();
            $dataArray['amp'] = $normalizationTarget->model($amp);
        }
        $backendOption = $this->backend;
        if ($backendOption->isDefined()) {
            $backend = $backendOption->get();
            $dataArray['backend'] = $normalizationTarget->model($backend);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ServiceInformationBuilder
    {
        return new ServiceInformationBuilder($this->amp, $this->backend, $this->additionalProperties);
    }
}
