<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Exception\MalformedDataException;
use Prefabcortex\DhlParcelDeShippingV2\Optional\None;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class ServiceInformationAmp implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $name
     * @param Option<string>           $env
     * @param Option<string>           $version
     * @param Option<string>           $rev
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $name,
        private Option $env,
        private Option $version,
        private Option $rev,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ServiceInformationAmpBuilder
    {
        return new ServiceInformationAmpBuilder(None::create(), None::create(), None::create(), None::create(), []);
    }

    /**
     * name of api.
     *
     * @return Option<string>
     */
    public function getName(): Option
    {
        return $this->name;
    }

    /**
     * environment.
     *
     * @return Option<string>
     */
    public function getEnv(): Option
    {
        return $this->env;
    }

    /**
     * version of api.
     *
     * @return Option<string>
     */
    public function getVersion(): Option
    {
        return $this->version;
    }

    /**
     * revision.
     *
     * @return Option<string>
     */
    public function getRev(): Option
    {
        return $this->rev;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $name = None::create();
        $env = None::create();
        $version = None::create();
        $rev = None::create();
        if (array_key_exists('name', $data) && $data['name'] !== null) {
            $nameRaw = $data['name'];
            if (!is_string($nameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "name" must be string, got %s.', get_debug_type($nameRaw)),
                );
            }
            $name = Some::create($nameRaw);
        }
        if (array_key_exists('env', $data) && $data['env'] !== null) {
            $envRaw = $data['env'];
            if (!is_string($envRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "env" must be string, got %s.', get_debug_type($envRaw)),
                );
            }
            $env = Some::create($envRaw);
        }
        if (array_key_exists('version', $data) && $data['version'] !== null) {
            $versionRaw = $data['version'];
            if (!is_string($versionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "version" must be string, got %s.', get_debug_type($versionRaw)),
                );
            }
            $version = Some::create($versionRaw);
        }
        if (array_key_exists('rev', $data) && $data['rev'] !== null) {
            $revRaw = $data['rev'];
            if (!is_string($revRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "rev" must be string, got %s.', get_debug_type($revRaw)),
                );
            }
            $rev = Some::create($revRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['name' => true, 'env' => true, 'version' => true, 'rev' => true],
        );

        return new self($name, $env, $version, $rev, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $nameOption = $this->name;
        if ($nameOption->isDefined()) {
            $name = $nameOption->get();
            $dataArray['name'] = $name;
        }
        $envOption = $this->env;
        if ($envOption->isDefined()) {
            $env = $envOption->get();
            $dataArray['env'] = $env;
        }
        $versionOption = $this->version;
        if ($versionOption->isDefined()) {
            $version = $versionOption->get();
            $dataArray['version'] = $version;
        }
        $revOption = $this->rev;
        if ($revOption->isDefined()) {
            $rev = $revOption->get();
            $dataArray['rev'] = $rev;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ServiceInformationAmpBuilder
    {
        return new ServiceInformationAmpBuilder(
            $this->name,
            $this->env,
            $this->version,
            $this->rev,
            $this->additionalProperties,
        );
    }
}
