<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

/**
 * Builds a {@see ServiceInformation}.
 */
final class ServiceInformationBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<ServiceInformationAmp>     $amp
     * @param Option<ServiceInformationBackend> $backend
     * @param array<int|string, mixed>          $additionalProperties
     */
    public function __construct(private Option $amp, private Option $backend, private array $additionalProperties)
    {
    }

    public function setAmp(ServiceInformationAmp $amp): self
    {
        $this->amp = Some::create($amp);

        return $this;
    }

    public function setBackend(ServiceInformationBackend $backend): self
    {
        $this->backend = Some::create($backend);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ServiceInformation
    {
        return new ServiceInformation($this->amp, $this->backend, $this->additionalProperties);
    }
}
