<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Exception\MalformedDataException;
use Prefabcortex\DhlParcelDeShippingV2\Optional\None;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class ShipmentManifestingRequest implements SelfNormalizingModel
{
    /**
     * @param Option<list<string>>     $shipmentNumbers
     * @param Option<string>           $billingNumber
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $profile,
        private Option $shipmentNumbers,
        private Option $billingNumber,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $profile): ShipmentManifestingRequestBuilder
    {
        return new ShipmentManifestingRequestBuilder($profile, None::create(), None::create(), []);
    }

    public function getProfile(): string
    {
        return $this->profile;
    }

    /**
     * List of shipment IDs for manifesting.
     *
     * @return Option<list<string>>
     */
    public function getShipmentNumbers(): Option
    {
        return $this->shipmentNumbers;
    }

    /**
     * Customer billingNumber number.
     *
     * @return Option<string>
     */
    public function getBillingNumber(): Option
    {
        return $this->billingNumber;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $profile = null;
        $shipmentNumbers = None::create();
        $billingNumber = None::create();
        if (array_key_exists('profile', $data)) {
            $profileRaw = $data['profile'];
            if (!is_string($profileRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "profile" must be string, got %s.', get_debug_type($profileRaw)),
                );
            }
            $profile = $profileRaw;
        }
        if (array_key_exists('shipmentNumbers', $data) && $data['shipmentNumbers'] !== null) {
            $shipmentNumbersRaw = $data['shipmentNumbers'];
            if (!(is_array($shipmentNumbersRaw) && array_is_list($shipmentNumbersRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "shipmentNumbers" must be list, got %s.', get_debug_type($shipmentNumbersRaw)),
                );
            }
            $shipmentNumbers = Some::create(array_map(static function (mixed $value): string {
                if (!is_string($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value)),
                    );
                }

                return $value;
            }, $shipmentNumbersRaw));
        }
        if (array_key_exists('billingNumber', $data) && $data['billingNumber'] !== null) {
            $billingNumberRaw = $data['billingNumber'];
            if (!is_string($billingNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "billingNumber" must be string, got %s.', get_debug_type($billingNumberRaw)),
                );
            }
            $billingNumber = Some::create($billingNumberRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['profile' => true, 'shipmentNumbers' => true, 'billingNumber' => true],
        );
        if ($profile === null) {
            throw new MalformedDataException('Required property "profile" is missing from the document.');
        }

        return new self($profile, $shipmentNumbers, $billingNumber, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['profile'] = $this->profile;
        $shipmentNumbersOption = $this->shipmentNumbers;
        if ($shipmentNumbersOption->isDefined()) {
            $shipmentNumbers = $shipmentNumbersOption->get();
            $values = [];
            foreach ($shipmentNumbers as $value) {
                $values[] = $value;
            }
            $dataArray['shipmentNumbers'] = $values;
        }
        $billingNumberOption = $this->billingNumber;
        if ($billingNumberOption->isDefined()) {
            $billingNumber = $billingNumberOption->get();
            $dataArray['billingNumber'] = $billingNumber;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ShipmentManifestingRequestBuilder
    {
        return new ShipmentManifestingRequestBuilder(
            $this->profile,
            $this->shipmentNumbers,
            $this->billingNumber,
            $this->additionalProperties,
        );
    }
}
