<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

/**
 * Builds a {@see ShipmentNoToSheetNo}.
 */
final class ShipmentNoToSheetNoBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $shipmentNo
     * @param Option<string>           $sheetNo
     * @param Option<RequestStatus>    $sstatus
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $shipmentNo,
        private Option $sheetNo,
        private Option $sstatus,
        private array $additionalProperties,
    ) {
    }

    public function setShipmentNo(string $shipmentNo): self
    {
        $this->shipmentNo = Some::create($shipmentNo);

        return $this;
    }

    public function setSheetNo(string $sheetNo): self
    {
        $this->sheetNo = Some::create($sheetNo);

        return $this;
    }

    /**
     * General status description for the attached response or response item.
     */
    public function setSstatus(RequestStatus $sstatus): self
    {
        $this->sstatus = Some::create($sstatus);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentNoToSheetNo
    {
        return new ShipmentNoToSheetNo($this->shipmentNo, $this->sheetNo, $this->sstatus, $this->additionalProperties);
    }
}
