<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class ShipperReference implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(private string $shipperRef, private array $additionalProperties)
    {
    }

    public static function builder(string $shipperRef): ShipperReferenceBuilder
    {
        return new ShipperReferenceBuilder($shipperRef, []);
    }

    /**
     * Reference string to the shipper data configured in GKP(GeschÃ¤ftskundenportal - Business
     * Costumer Portal).
     */
    public function getShipperRef(): string
    {
        return $this->shipperRef;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $shipperRef = null;
        if (array_key_exists('shipperRef', $data)) {
            $shipperRefRaw = $data['shipperRef'];
            if (!is_string($shipperRefRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "shipperRef" must be string, got %s.', get_debug_type($shipperRefRaw)),
                );
            }
            $shipperRef = $shipperRefRaw;
        }
        $additionalProperties = array_diff_key($data, ['shipperRef' => true]);
        if ($shipperRef === null) {
            throw new MalformedDataException('Required property "shipperRef" is missing from the document.');
        }

        return new self($shipperRef, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['shipperRef'] = $this->shipperRef;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ShipperReferenceBuilder
    {
        return new ShipperReferenceBuilder($this->shipperRef, $this->additionalProperties);
    }
}
