<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

/**
 * Builds a {@see ShipmentOrderRequest}.
 */
final class ShipmentOrderRequestBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param list<Shipment>           $shipments
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private string $profile, private array $shipments, private array $additionalProperties)
    {
    }

    public function setProfile(string $profile): self
    {
        $this->profile = $profile;

        return $this;
    }

    /**
     * Shipment array having details for each shipment.
     *
     * @param list<Shipment> $shipments
     */
    public function setShipments(array $shipments): self
    {
        $this->shipments = $shipments;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentOrderRequest
    {
        return new ShipmentOrderRequest($this->profile, $this->shipments, $this->additionalProperties);
    }
}
