<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

/**
 * Builds a {@see Shipper}.
 */
final class ShipperBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Country|UnknownEnumValue<string> $country
     * @param Option<string>                   $name2
     * @param Option<string>                   $name3
     * @param Option<string>                   $addressHouse
     * @param Option<string>                   $postalCode
     * @param Option<string>                   $contactName
     * @param Option<string>                   $email
     * @param array<int|string, mixed>         $additionalProperties
     */
    public function __construct(
        private string $name1,
        private string $addressStreet,
        private string $city,
        private Country|UnknownEnumValue $country,
        private Option $name2,
        private Option $name3,
        private Option $addressHouse,
        private Option $postalCode,
        private Option $contactName,
        private Option $email,
        private array $additionalProperties,
    ) {
    }

    /**
     * Name1. Line 1 of name information.
     */
    public function setName1(string $name1): self
    {
        $this->name1 = $name1;

        return $this;
    }

    /**
     * Line 1 of the street address. This is just the street name. Can also include house number.
     */
    public function setAddressStreet(string $addressStreet): self
    {
        $this->addressStreet = $addressStreet;

        return $this;
    }

    /**
     * city.
     */
    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * A valid country code consisting of three characters according to ISO 3166-1 alpha-3.
     */
    public function setCountry(Country $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * An optional, additional line of name information.
     */
    public function setName2(string $name2): self
    {
        $this->name2 = Some::create($name2);

        return $this;
    }

    /**
     * An optional, additional line of name information.
     */
    public function setName3(string $name3): self
    {
        $this->name3 = Some::create($name3);

        return $this;
    }

    /**
     * Line 1 of the street address. This is just the house number. Can be added to street name
     * instead.
     */
    public function setAddressHouse(string $addressHouse): self
    {
        $this->addressHouse = Some::create($addressHouse);

        return $this;
    }

    /**
     * Mandatory for all countries but Ireland that use a postal code system.
     */
    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = Some::create($postalCode);

        return $this;
    }

    /**
     * optional contact name. (this is not the primary name printed on label).
     */
    public function setContactName(string $contactName): self
    {
        $this->contactName = Some::create($contactName);

        return $this;
    }

    /**
     * Optional contact email address of the shipper.
     */
    public function setEmail(string $email): self
    {
        $this->email = Some::create($email);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Shipper
    {
        return new Shipper(
            $this->name1,
            $this->addressStreet,
            $this->city,
            $this->country,
            $this->name2,
            $this->name3,
            $this->addressHouse,
            $this->postalCode,
            $this->contactName,
            $this->email,
            $this->additionalProperties,
        );
    }
}
