<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use DateTime;
use DateTimeInterface;
use Override;
use Prefabcortex\DhlParcelDeShippingV2\Exception\MalformedDataException;
use Prefabcortex\DhlParcelDeShippingV2\Optional\None;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_int;
use function is_string;
use function sprintf;

final readonly class Shipment implements SelfNormalizingModel
{
    /**
     * @param Option<Product|UnknownEnumValue<string>>       $product
     * @param Option<string>                                 $billingNumber
     * @param Option<string>                                 $refNo
     * @param Option<string>                                 $costCenter
     * @param Option<string>                                 $creationSoftware
     * @param Option<DateTimeInterface>                      $shipDate
     * @param Option<Shipper|ShipperReference>               $shipper
     * @param Option<ContactAddress|Locker|PostOffice|POBox> $consignee
     * @param Option<ShipmentDetails>                        $details
     * @param Option<VAS>                                    $services
     * @param Option<CustomsDetails>                         $customs
     * @param array<int|string, mixed>                       $additionalProperties
     */
    public function __construct(
        private Option $product,
        private Option $billingNumber,
        private Option $refNo,
        private Option $costCenter,
        private Option $creationSoftware,
        private Option $shipDate,
        private Option $shipper,
        private Option $consignee,
        private Option $details,
        private Option $services,
        private Option $customs,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ShipmentBuilder
    {
        return new ShipmentBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Determines the DHL Paket product to be used.
     *
     * * V01PAK: DHL PAKET;
     * * V53WPAK: DHL PAKET International;
     * * V54EPAK: DHL Europaket;
     * * V62WP: Warenpost (will be replaced by DHL Kleinpaket from 1.1.2025);
     * * V62KP: DHL Kleinpaket;
     * * V66WPI: Warenpost International
     *
     * @return Option<Product|UnknownEnumValue<string>>
     */
    public function getProduct(): Option
    {
        return $this->product;
    }

    /**
     * 14 digit long number that identifies the contract the shipment is booked on. Please note that
     * in rare cases the last to characters can be letters. Digit 11 and digit 12 must correspondent
     * to the number of the product, e.g. 333333333301tt can only be used for the product V01PAK
     * (DHL Paket).
     *
     * @return Option<string>
     */
    public function getBillingNumber(): Option
    {
        return $this->billingNumber;
    }

    /**
     * A reference number that the user can assign for better association purposes. It appears on
     * shipment labels. To use the reference number for tracking purposes, it should be at least 8
     * characters long and unique.
     *
     * @return Option<string>
     */
    public function getRefNo(): Option
    {
        return $this->refNo;
    }

    /**
     * Textfield that appears on the shipment label. It cannot be used to search for the shipment.
     *
     * @return Option<string>
     */
    public function getCostCenter(): Option
    {
        return $this->costCenter;
    }

    /**
     * Is only to be indicated by DHL partners.
     *
     * @return Option<string>
     */
    public function getCreationSoftware(): Option
    {
        return $this->creationSoftware;
    }

    /**
     * Date the shipment is transferred to DHL. The shipment date can be the current date or a date
     * up to a few days in the future. It must not be in the past. Iso format required: yyyy-mm-dd.
     * On the shipment date the shipment will be automatically closed at your end of day closing
     * time.
     *
     * @return Option<DateTimeInterface>
     */
    public function getShipDate(): Option
    {
        return $this->shipDate;
    }

    /**
     * Shipper information, including contact information and address. Alternatively, a predefined
     * shipper reference can be used.
     *
     * @return Option<Shipper|ShipperReference>
     */
    public function getShipper(): Option
    {
        return $this->shipper;
    }

    /**
     * Consignee address information. Either a doorstep address (contact address) including contact
     * information or a droppoint address. One of packstation (parcel locker), or post office
     * (postfiliale/retail shop).
     *
     * @return Option<ContactAddress|Locker|PostOffice|POBox>
     */
    public function getConsignee(): Option
    {
        return $this->consignee;
    }

    /**
     * Details for the shipment, such as dimensions, content.
     *
     * @return Option<ShipmentDetails>
     */
    public function getDetails(): Option
    {
        return $this->details;
    }

    /**
     * Value added services. Please note that services are specific to products and geographies
     * and/or may require individual setup and billing numbers. Please test and contact your account
     * representative in case of questions.
     *
     * @return Option<VAS>
     */
    public function getServices(): Option
    {
        return $this->services;
    }

    /**
     * For international shipments, this section contains information necessary for customs about
     * the exported goods. ExportDocument can contain one or more positions as child element. This
     * data is also transferred as electronic declaration to customs. The custom details are
     * mandatory depending on whether the parcel will go to a country outside the European Customs
     * Union. For DHL Parcel International (V53WPAK) CN23 will returned as a separate document,
     * while for Warenpost International the customs information will be printed onto the shipment
     * label (CN22).
     *
     * @return Option<CustomsDetails>
     */
    public function getCustoms(): Option
    {
        return $this->customs;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $product = None::create();
        $billingNumber = None::create();
        $refNo = None::create();
        $costCenter = None::create();
        $creationSoftware = None::create();
        $shipDate = None::create();
        $shipper = None::create();
        $consignee = None::create();
        $details = None::create();
        $services = None::create();
        $customs = None::create();
        if (array_key_exists('product', $data) && $data['product'] !== null) {
            $productRaw = $data['product'];
            if (!is_string($productRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "product" must be string, got %s.', get_debug_type($productRaw)),
                );
            }
            $product = Some::create(Product::tryFrom($productRaw) ?? UnknownEnumValue::of($productRaw));
        }
        if (array_key_exists('billingNumber', $data) && $data['billingNumber'] !== null) {
            $billingNumberRaw = $data['billingNumber'];
            if (!is_string($billingNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "billingNumber" must be string, got %s.', get_debug_type($billingNumberRaw)),
                );
            }
            $billingNumber = Some::create($billingNumberRaw);
        }
        if (array_key_exists('refNo', $data) && $data['refNo'] !== null) {
            $refNoRaw = $data['refNo'];
            if (!is_string($refNoRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "refNo" must be string, got %s.', get_debug_type($refNoRaw)),
                );
            }
            $refNo = Some::create($refNoRaw);
        }
        if (array_key_exists('costCenter', $data) && $data['costCenter'] !== null) {
            $costCenterRaw = $data['costCenter'];
            if (!is_string($costCenterRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "costCenter" must be string, got %s.', get_debug_type($costCenterRaw)),
                );
            }
            $costCenter = Some::create($costCenterRaw);
        }
        if (array_key_exists('creationSoftware', $data) && $data['creationSoftware'] !== null) {
            $creationSoftwareRaw = $data['creationSoftware'];
            if (!is_string($creationSoftwareRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "creationSoftware" must be string, got %s.',
                        get_debug_type($creationSoftwareRaw),
                    ),
                );
            }
            $creationSoftware = Some::create($creationSoftwareRaw);
        }
        if (array_key_exists('shipDate', $data) && $data['shipDate'] !== null) {
            $shipDateRaw = $data['shipDate'];
            if (!is_string($shipDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "shipDate" must be string, got %s.', get_debug_type($shipDateRaw)),
                );
            }
            $date = DateTime::createFromFormat('Y-m-d', $shipDateRaw);
            if (false === $date || false !== DateTime::getLastErrors()) {
                throw new MalformedDataException('Invalid date format, expected: Y-m-d');
            }
            $shipDate = Some::create($date->setTime(0, 0, 0));
        }
        if (array_key_exists('shipper', $data) && $data['shipper'] !== null) {
            if (!is_array($data['shipper'])) {
                throw new MalformedDataException(
                    'Property "shipper" matched none of the expected shapes: Shipper, ShipperReference.',
                );
            }
            /** @var array<string, mixed> $shipperTyped */
            $shipperTyped = $data['shipper'];
            if (
                array_key_exists('name1', $shipperTyped)
                && array_key_exists('addressStreet', $shipperTyped)
                && array_key_exists('city', $shipperTyped)
                && (
                    array_key_exists('country', $shipperTyped)
                    && (
                        (is_int($shipperTyped['country']) || is_string($shipperTyped['country']))
                        && Country::tryFrom($shipperTyped['country']) !== null
                    )
                )
            ) {
                $value = Shipper::fromArray($shipperTyped);
            } elseif (array_key_exists('shipperRef', $shipperTyped)) {
                $value = ShipperReference::fromArray($shipperTyped);
            } else {
                throw new MalformedDataException(
                    'Property "shipper" matched none of the expected shapes: Shipper, ShipperReference.',
                );
            }
            $shipper = Some::create($value);
        }
        if (array_key_exists('consignee', $data) && $data['consignee'] !== null) {
            if (!is_array($data['consignee'])) {
                throw new MalformedDataException('Property "consignee" matched none of the expected shapes: ContactAddress, Locker, PostOffice, POBox.');
            }
            /** @var array<string, mixed> $consigneeTyped */
            $consigneeTyped = $data['consignee'];
            if (
                array_key_exists('name', $consigneeTyped)
                && array_key_exists('lockerID', $consigneeTyped)
                && array_key_exists('postNumber', $consigneeTyped)
                && array_key_exists('city', $consigneeTyped)
                && array_key_exists('postalCode', $consigneeTyped)
            ) {
                $value_1 = Locker::fromArray($consigneeTyped);
            } elseif (
                array_key_exists('name1', $consigneeTyped)
                && array_key_exists('addressStreet', $consigneeTyped)
                && array_key_exists('city', $consigneeTyped)
                && (
                    array_key_exists('country', $consigneeTyped)
                    && (
                        (is_int($consigneeTyped['country']) || is_string($consigneeTyped['country']))
                        && Country::tryFrom($consigneeTyped['country']) !== null
                    )
                )
            ) {
                $value_1 = ContactAddress::fromArray($consigneeTyped);
            } elseif (
                array_key_exists('name', $consigneeTyped)
                && array_key_exists('retailID', $consigneeTyped)
                && array_key_exists('city', $consigneeTyped)
                && array_key_exists('postalCode', $consigneeTyped)
            ) {
                $value_1 = PostOffice::fromArray($consigneeTyped);
            } elseif (
                array_key_exists('name1', $consigneeTyped)
                && array_key_exists('poBoxID', $consigneeTyped)
                && array_key_exists('city', $consigneeTyped)
                && array_key_exists('postalCode', $consigneeTyped)
            ) {
                $value_1 = POBox::fromArray($consigneeTyped);
            } else {
                throw new MalformedDataException('Property "consignee" matched none of the expected shapes: ContactAddress, Locker, PostOffice, POBox.');
            }
            $consignee = Some::create($value_1);
        }
        if (array_key_exists('details', $data) && $data['details'] !== null) {
            $detailsRaw = $data['details'];
            if (!is_array($detailsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "details" must be object, got %s.', get_debug_type($detailsRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $detailsRawTyped */
            $detailsRawTyped = $detailsRaw;
            $details = Some::create(ShipmentDetails::fromArray($detailsRawTyped));
        }
        if (array_key_exists('services', $data) && $data['services'] !== null) {
            $servicesRaw = $data['services'];
            if (!is_array($servicesRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "services" must be object, got %s.', get_debug_type($servicesRaw)),
                );
            }
            /** @var array<string, mixed> $servicesRawTyped */
            $servicesRawTyped = $servicesRaw;
            $services = Some::create(VAS::fromArray($servicesRawTyped));
        }
        if (array_key_exists('customs', $data) && $data['customs'] !== null) {
            $customsRaw = $data['customs'];
            if (!is_array($customsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "customs" must be object, got %s.', get_debug_type($customsRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $customsRawTyped */
            $customsRawTyped = $customsRaw;
            $customs = Some::create(CustomsDetails::fromArray($customsRawTyped));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'product' => true,
                'billingNumber' => true,
                'refNo' => true,
                'costCenter' => true,
                'creationSoftware' => true,
                'shipDate' => true,
                'shipper' => true,
                'consignee' => true,
                'details' => true,
                'services' => true,
                'customs' => true,
            ],
        );

        return new self(
            $product,
            $billingNumber,
            $refNo,
            $costCenter,
            $creationSoftware,
            $shipDate,
            $shipper,
            $consignee,
            $details,
            $services,
            $customs,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $productOption = $this->product;
        if ($productOption->isDefined()) {
            $product = $productOption->get();
            $dataArray['product'] = $product->value;
        }
        $billingNumberOption = $this->billingNumber;
        if ($billingNumberOption->isDefined()) {
            $billingNumber = $billingNumberOption->get();
            $dataArray['billingNumber'] = $billingNumber;
        }
        $refNoOption = $this->refNo;
        if ($refNoOption->isDefined()) {
            $refNo = $refNoOption->get();
            $dataArray['refNo'] = $refNo;
        }
        $costCenterOption = $this->costCenter;
        if ($costCenterOption->isDefined()) {
            $costCenter = $costCenterOption->get();
            $dataArray['costCenter'] = $costCenter;
        }
        $creationSoftwareOption = $this->creationSoftware;
        if ($creationSoftwareOption->isDefined()) {
            $creationSoftware = $creationSoftwareOption->get();
            $dataArray['creationSoftware'] = $creationSoftware;
        }
        $shipDateOption = $this->shipDate;
        if ($shipDateOption->isDefined()) {
            $shipDate = $shipDateOption->get();
            $dataArray['shipDate'] = $shipDate->format('Y-m-d');
        }
        $shipperOption = $this->shipper;
        if ($shipperOption->isDefined()) {
            $shipper = $shipperOption->get();
            $value = $normalizationTarget->model($shipper);
            $dataArray['shipper'] = $value;
        }
        $consigneeOption = $this->consignee;
        if ($consigneeOption->isDefined()) {
            $consignee = $consigneeOption->get();
            $value_1 = $normalizationTarget->model($consignee);
            $dataArray['consignee'] = $value_1;
        }
        $detailsOption = $this->details;
        if ($detailsOption->isDefined()) {
            $details = $detailsOption->get();
            $dataArray['details'] = $normalizationTarget->model($details);
        }
        $servicesOption = $this->services;
        if ($servicesOption->isDefined()) {
            $services = $servicesOption->get();
            $dataArray['services'] = $normalizationTarget->model($services);
        }
        $customsOption = $this->customs;
        if ($customsOption->isDefined()) {
            $customs = $customsOption->get();
            $dataArray['customs'] = $normalizationTarget->model($customs);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ShipmentBuilder
    {
        return new ShipmentBuilder(
            $this->product,
            $this->billingNumber,
            $this->refNo,
            $this->costCenter,
            $this->creationSoftware,
            $this->shipDate,
            $this->shipper,
            $this->consignee,
            $this->details,
            $this->services,
            $this->customs,
            $this->additionalProperties,
        );
    }
}
