<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

/**
 * Builds a {@see ShortResponseItem}.
 */
final class ShortResponseItemBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $shipmentNo
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private RequestStatus $sstatus,
        private Option $shipmentNo,
        private array $additionalProperties,
    ) {
    }

    /**
     * General status description for the attached response or response item.
     */
    public function setSstatus(RequestStatus $sstatus): self
    {
        $this->sstatus = $sstatus;

        return $this;
    }

    public function setShipmentNo(string $shipmentNo): self
    {
        $this->shipmentNo = Some::create($shipmentNo);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShortResponseItem
    {
        return new ShortResponseItem($this->sstatus, $this->shipmentNo, $this->additionalProperties);
    }
}
