<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Exception\MalformedDataException;
use Prefabcortex\DhlParcelDeShippingV2\Optional\None;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class ShortResponseItem implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $shipmentNo
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private RequestStatus $sstatus,
        private Option $shipmentNo,
        private array $additionalProperties,
    ) {
    }

    public static function builder(RequestStatus $sstatus): ShortResponseItemBuilder
    {
        return new ShortResponseItemBuilder($sstatus, None::create(), []);
    }

    /** @return Option<string> */
    public function getShipmentNo(): Option
    {
        return $this->shipmentNo;
    }

    /**
     * General status description for the attached response or response item.
     */
    public function getSstatus(): RequestStatus
    {
        return $this->sstatus;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $shipmentNo = None::create();
        $sstatus = null;
        if (array_key_exists('shipmentNo', $data) && $data['shipmentNo'] !== null) {
            $shipmentNoRaw = $data['shipmentNo'];
            if (!is_string($shipmentNoRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "shipmentNo" must be string, got %s.', get_debug_type($shipmentNoRaw)),
                );
            }
            $shipmentNo = Some::create($shipmentNoRaw);
        }
        if (array_key_exists('sstatus', $data)) {
            $sstatusRaw = $data['sstatus'];
            if (!is_array($sstatusRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "sstatus" must be object, got %s.', get_debug_type($sstatusRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $sstatusRawTyped */
            $sstatusRawTyped = $sstatusRaw;
            $sstatus = RequestStatus::fromArray($sstatusRawTyped);
        }
        $additionalProperties = array_diff_key($data, ['shipmentNo' => true, 'sstatus' => true]);
        if ($sstatus === null) {
            throw new MalformedDataException('Required property "sstatus" is missing from the document.');
        }

        return new self($sstatus, $shipmentNo, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $shipmentNoOption = $this->shipmentNo;
        if ($shipmentNoOption->isDefined()) {
            $shipmentNo = $shipmentNoOption->get();
            $dataArray['shipmentNo'] = $shipmentNo;
        }
        $dataArray['sstatus'] = $normalizationTarget->model($this->sstatus);
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ShortResponseItemBuilder
    {
        return new ShortResponseItemBuilder($this->sstatus, $this->shipmentNo, $this->additionalProperties);
    }
}
