<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

/**
 * Builds a {@see SingleManifestResponse}.
 */
final class SingleManifestResponseBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<RequestStatus>             $status
     * @param Option<string>                    $manifestDate
     * @param Option<list<Document>>            $manifest
     * @param Option<list<BillingNoToSheetNo>>  $sheetNo
     * @param Option<list<ShipmentNoToSheetNo>> $items
     * @param array<int|string, mixed>          $additionalProperties
     */
    public function __construct(
        private Option $status,
        private Option $manifestDate,
        private Option $manifest,
        private Option $sheetNo,
        private Option $items,
        private array $additionalProperties,
    ) {
    }

    /**
     * General status description for the attached response or response item.
     */
    public function setStatus(RequestStatus $status): self
    {
        $this->status = Some::create($status);

        return $this;
    }

    public function setManifestDate(string $manifestDate): self
    {
        $this->manifestDate = Some::create($manifestDate);

        return $this;
    }

    /** @param list<Document> $manifest */
    public function setManifest(array $manifest): self
    {
        $this->manifest = Some::create($manifest);

        return $this;
    }

    /** @param list<BillingNoToSheetNo> $sheetNo */
    public function setSheetNo(array $sheetNo): self
    {
        $this->sheetNo = Some::create($sheetNo);

        return $this;
    }

    /** @param list<ShipmentNoToSheetNo> $items */
    public function setItems(array $items): self
    {
        $this->items = Some::create($items);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): SingleManifestResponse
    {
        return new SingleManifestResponse(
            $this->status,
            $this->manifestDate,
            $this->manifest,
            $this->sheetNo,
            $this->items,
            $this->additionalProperties,
        );
    }
}
