<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

/**
 * Builds a {@see Value}.
 */
final class ValueBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param ValueCurrency|UnknownEnumValue<string> $currency
     * @param array<int|string, mixed>               $additionalProperties
     */
    public function __construct(
        private ValueCurrency|UnknownEnumValue $currency,
        private float $value,
        private array $additionalProperties,
    ) {
    }

    /**
     * iso 4217 3 character currency code accepted. Recommended to use EUR where possible.
     */
    public function setCurrency(ValueCurrency $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * Numeric value.
     */
    public function setValue(float $value): self
    {
        $this->value = $value;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Value
    {
        return new Value($this->currency, $this->value, $this->additionalProperties);
    }
}
