<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use DateTimeInterface;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

/**
 * Builds a {@see VAS}.
 */
final class VASBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                                       $preferredNeighbour
     * @param Option<string>                                       $preferredLocation
     * @param Option<VASVisualCheckOfAge|UnknownEnumValue<string>> $visualCheckOfAge
     * @param Option<bool>                                         $namedPersonOnly
     * @param Option<VASIdentCheck>                                $identCheck
     * @param Option<bool>                                         $signedForByRecipient
     * @param Option<VASEndorsement|UnknownEnumValue<string>>      $endorsement
     * @param Option<DateTimeInterface>                            $preferredDay
     * @param Option<bool>                                         $noNeighbourDelivery
     * @param Option<Value>                                        $additionalInsurance
     * @param Option<bool>                                         $bulkyGoods
     * @param Option<VASCashOnDelivery>                            $cashOnDelivery
     * @param Option<string>                                       $individualSenderRequirement
     * @param Option<bool>                                         $premium
     * @param Option<bool>                                         $closestDropPoint
     * @param Option<string>                                       $parcelOutletRouting
     * @param Option<bool>                                         $goGreenPlus
     * @param Option<VASDhlRetoure>                                $dhlRetoure
     * @param Option<bool>                                         $postalDeliveryDutyPaid
     * @param array<int|string, mixed>                             $additionalProperties
     */
    public function __construct(
        private Option $preferredNeighbour,
        private Option $preferredLocation,
        private Option $visualCheckOfAge,
        private Option $namedPersonOnly,
        private Option $identCheck,
        private Option $signedForByRecipient,
        private Option $endorsement,
        private Option $preferredDay,
        private Option $noNeighbourDelivery,
        private Option $additionalInsurance,
        private Option $bulkyGoods,
        private Option $cashOnDelivery,
        private Option $individualSenderRequirement,
        private Option $premium,
        private Option $closestDropPoint,
        private Option $parcelOutletRouting,
        private Option $goGreenPlus,
        private Option $dhlRetoure,
        private Option $postalDeliveryDutyPaid,
        private array $additionalProperties,
    ) {
    }

    /**
     * Preferred neighbour. Can be specified as text.
     */
    public function setPreferredNeighbour(string $preferredNeighbour): self
    {
        $this->preferredNeighbour = Some::create($preferredNeighbour);

        return $this;
    }

    /**
     * Preferred location. Can be specified as text.
     */
    public function setPreferredLocation(string $preferredLocation): self
    {
        $this->preferredLocation = Some::create($preferredLocation);

        return $this;
    }

    /**
     * if used it will trigger checking the age of recipient.
     */
    public function setVisualCheckOfAge(VASVisualCheckOfAge $visualCheckOfAge): self
    {
        $this->visualCheckOfAge = Some::create($visualCheckOfAge);

        return $this;
    }

    /**
     * Delivery can only be signed for by yourself personally.
     */
    public function setNamedPersonOnly(bool $namedPersonOnly): self
    {
        $this->namedPersonOnly = Some::create($namedPersonOnly);

        return $this;
    }

    /**
     * Check the identity of the recipient via name (firstname, lastname), date of birth or age.
     * This uses firstName and lastName as separate attributes since for identity check an automatic
     * split of a one-line name is not considered reliable enough.
     */
    public function setIdentCheck(VASIdentCheck $identCheck): self
    {
        $this->identCheck = Some::create($identCheck);

        return $this;
    }

    /**
     * Delivery must be signed for by the recipient and not by DHL staff.
     */
    public function setSignedForByRecipient(bool $signedForByRecipient): self
    {
        $this->signedForByRecipient = Some::create($signedForByRecipient);

        return $this;
    }

    /**
     * Instructions and endorsement how to treat international undeliverable shipment. By default,
     * shipments are returned if undeliverable. There are country specific rules whether the
     * shipment is returned immediately or after a grace period.
     */
    public function setEndorsement(VASEndorsement $endorsement): self
    {
        $this->endorsement = Some::create($endorsement);

        return $this;
    }

    /**
     * Preferred day of delivery in format YYYY-MM-DD. Shipper can request a preferred day of
     * delivery. The preferred day should be between 2 and 6 working days after handover to DHL.
     */
    public function setPreferredDay(DateTimeInterface $preferredDay): self
    {
        $this->preferredDay = Some::create($preferredDay);

        return $this;
    }

    /**
     * Delivery can only be signed for by yourself personally or by members of your household.
     */
    public function setNoNeighbourDelivery(bool $noNeighbourDelivery): self
    {
        $this->noNeighbourDelivery = Some::create($noNeighbourDelivery);

        return $this;
    }

    /**
     * Currency and numeric value.
     */
    public function setAdditionalInsurance(Value $additionalInsurance): self
    {
        $this->additionalInsurance = Some::create($additionalInsurance);

        return $this;
    }

    /**
     * Leaving this out is same as setting to false. Sperrgut.
     */
    public function setBulkyGoods(bool $bulkyGoods): self
    {
        $this->bulkyGoods = Some::create($bulkyGoods);

        return $this;
    }

    /**
     * Cash on delivery (Nachnahme). Currency must be Euro. Either bank account information or
     * account reference (from customer profile) must be provided. Transfernote1 + 2 are references
     * transmitted during bank transfer. Providing account information explicitly requires elevated
     * privileges.
     */
    public function setCashOnDelivery(VASCashOnDelivery $cashOnDelivery): self
    {
        $this->cashOnDelivery = Some::create($cashOnDelivery);

        return $this;
    }

    /**
     * Special instructions for delivery. 2 character code, possible values agreed in contract.
     */
    public function setIndividualSenderRequirement(string $individualSenderRequirement): self
    {
        $this->individualSenderRequirement = Some::create($individualSenderRequirement);

        return $this;
    }

    /**
     * Choice of premium vs economy parcel. Availability is country dependent and may be manipulated
     * by DHL if choice is not available. Please review the label.
     */
    public function setPremium(bool $premium): self
    {
        $this->premium = Some::create($premium);

        return $this;
    }

    /**
     * Closest Droppoint Delivery to the droppoint closest to the address of the recipient of the
     * shipment. For this kind of delivery either the phone number and/or the e-mail address of the
     * receiver is mandatory. For shipments using DHL Paket International it is recommended that you
     * choose one of the three delivery types: Economy, Premium, CDP. Otherwise, the current default
     * for the receiver country will be picked.
     */
    public function setClosestDropPoint(bool $closestDropPoint): self
    {
        $this->closestDropPoint = Some::create($closestDropPoint);

        return $this;
    }

    /**
     * Undeliverable domestic shipment can be forwarded and held at retail. Notification to email
     * (fallback: consignee email) will be used.
     */
    public function setParcelOutletRouting(string $parcelOutletRouting): self
    {
        $this->parcelOutletRouting = Some::create($parcelOutletRouting);

        return $this;
    }

    /**
     * GoGreen Plus enables sustainable shipping by investing in measures to reduce greenhouse gas
     * emissions at DHL.
     */
    public function setGoGreenPlus(bool $goGreenPlus): self
    {
        $this->goGreenPlus = Some::create($goGreenPlus);

        return $this;
    }

    /**
     * Requests return label (aka 'retoure') to be provided. Also requires returnAddress and return
     * billing number. Neither weight nor dimension need to be specified for the retoure (flat rate
     * service).
     */
    public function setDhlRetoure(VASDhlRetoure $dhlRetoure): self
    {
        $this->dhlRetoure = Some::create($dhlRetoure);

        return $this;
    }

    /**
     * All import duties are paid by the shipper.
     */
    public function setPostalDeliveryDutyPaid(bool $postalDeliveryDutyPaid): self
    {
        $this->postalDeliveryDutyPaid = Some::create($postalDeliveryDutyPaid);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): VAS
    {
        return new VAS(
            $this->preferredNeighbour,
            $this->preferredLocation,
            $this->visualCheckOfAge,
            $this->namedPersonOnly,
            $this->identCheck,
            $this->signedForByRecipient,
            $this->endorsement,
            $this->preferredDay,
            $this->noNeighbourDelivery,
            $this->additionalInsurance,
            $this->bulkyGoods,
            $this->cashOnDelivery,
            $this->individualSenderRequirement,
            $this->premium,
            $this->closestDropPoint,
            $this->parcelOutletRouting,
            $this->goGreenPlus,
            $this->dhlRetoure,
            $this->postalDeliveryDutyPaid,
            $this->additionalProperties,
        );
    }
}
