<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Exception\MalformedDataException;
use Prefabcortex\DhlParcelDeShippingV2\Optional\None;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class VASCashOnDelivery implements SelfNormalizingModel
{
    /**
     * @param Option<Value>            $amount
     * @param Option<BankAccount>      $bankAccount
     * @param Option<string>           $accountReference
     * @param Option<string>           $transferNote2
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $transferNote1,
        private Option $amount,
        private Option $bankAccount,
        private Option $accountReference,
        private Option $transferNote2,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $transferNote1): VASCashOnDeliveryBuilder
    {
        return new VASCashOnDeliveryBuilder(
            $transferNote1,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Currency and numeric value.
     *
     * @return Option<Value>
     */
    public function getAmount(): Option
    {
        return $this->amount;
    }

    /**
     * Bank account data used for CoD (Cash on Delivery).
     *
     * @return Option<BankAccount>
     */
    public function getBankAccount(): Option
    {
        return $this->bankAccount;
    }

    /**
     * Reference to bank account details. Account references are maintained in customer settings in
     * Post & DHL business customer portal under Ship -> Settings -> Cash on delivery. Please note,
     * that the default account reference is used if the provided account reference does not exist
     * in your customer settings!
     *
     * @return Option<string>
     */
    public function getAccountReference(): Option
    {
        return $this->accountReference;
    }

    public function getTransferNote1(): string
    {
        return $this->transferNote1;
    }

    /** @return Option<string> */
    public function getTransferNote2(): Option
    {
        return $this->transferNote2;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $amount = None::create();
        $bankAccount = None::create();
        $accountReference = None::create();
        $transferNote1 = null;
        $transferNote2 = None::create();
        if (array_key_exists('amount', $data) && $data['amount'] !== null) {
            $amountRaw = $data['amount'];
            if (!is_array($amountRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "amount" must be object, got %s.', get_debug_type($amountRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $amountRawTyped */
            $amountRawTyped = $amountRaw;
            $amount = Some::create(Value::fromArray($amountRawTyped));
        }
        if (array_key_exists('bankAccount', $data) && $data['bankAccount'] !== null) {
            $bankAccountRaw = $data['bankAccount'];
            if (!is_array($bankAccountRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "bankAccount" must be object, got %s.', get_debug_type($bankAccountRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $bankAccountRawTyped */
            $bankAccountRawTyped = $bankAccountRaw;
            $bankAccount = Some::create(BankAccount::fromArray($bankAccountRawTyped));
        }
        if (array_key_exists('accountReference', $data) && $data['accountReference'] !== null) {
            $accountReferenceRaw = $data['accountReference'];
            if (!is_string($accountReferenceRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "accountReference" must be string, got %s.',
                        get_debug_type($accountReferenceRaw),
                    ),
                );
            }
            $accountReference = Some::create($accountReferenceRaw);
        }
        if (array_key_exists('transferNote1', $data)) {
            $transferNote1Raw = $data['transferNote1'];
            if (!is_string($transferNote1Raw)) {
                throw new MalformedDataException(
                    sprintf('Property "transferNote1" must be string, got %s.', get_debug_type($transferNote1Raw)),
                );
            }
            $transferNote1 = $transferNote1Raw;
        }
        if (array_key_exists('transferNote2', $data) && $data['transferNote2'] !== null) {
            $transferNote2Raw = $data['transferNote2'];
            if (!is_string($transferNote2Raw)) {
                throw new MalformedDataException(
                    sprintf('Property "transferNote2" must be string, got %s.', get_debug_type($transferNote2Raw)),
                );
            }
            $transferNote2 = Some::create($transferNote2Raw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'amount' => true,
                'bankAccount' => true,
                'accountReference' => true,
                'transferNote1' => true,
                'transferNote2' => true,
            ],
        );
        if ($transferNote1 === null) {
            throw new MalformedDataException('Required property "transferNote1" is missing from the document.');
        }

        return new self(
            $transferNote1,
            $amount,
            $bankAccount,
            $accountReference,
            $transferNote2,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $amountOption = $this->amount;
        if ($amountOption->isDefined()) {
            $amount = $amountOption->get();
            $dataArray['amount'] = $normalizationTarget->model($amount);
        }
        $bankAccountOption = $this->bankAccount;
        if ($bankAccountOption->isDefined()) {
            $bankAccount = $bankAccountOption->get();
            $dataArray['bankAccount'] = $normalizationTarget->model($bankAccount);
        }
        $accountReferenceOption = $this->accountReference;
        if ($accountReferenceOption->isDefined()) {
            $accountReference = $accountReferenceOption->get();
            $dataArray['accountReference'] = $accountReference;
        }
        $dataArray['transferNote1'] = $this->transferNote1;
        $transferNote2Option = $this->transferNote2;
        if ($transferNote2Option->isDefined()) {
            $transferNote2 = $transferNote2Option->get();
            $dataArray['transferNote2'] = $transferNote2;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): VASCashOnDeliveryBuilder
    {
        return new VASCashOnDeliveryBuilder(
            $this->transferNote1,
            $this->amount,
            $this->bankAccount,
            $this->accountReference,
            $this->transferNote2,
            $this->additionalProperties,
        );
    }
}
