<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

/**
 * Builds a {@see VASDhlRetoure}.
 */
final class VASDhlRetoureBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $refNo
     * @param Option<ContactAddress>   $returnAddress
     * @param Option<bool>             $goGreenPlus
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $billingNumber,
        private Option $refNo,
        private Option $returnAddress,
        private Option $goGreenPlus,
        private array $additionalProperties,
    ) {
    }

    public function setBillingNumber(string $billingNumber): self
    {
        $this->billingNumber = $billingNumber;

        return $this;
    }

    public function setRefNo(string $refNo): self
    {
        $this->refNo = Some::create($refNo);

        return $this;
    }

    /**
     * Combines name, address, contact information. The recommended way is to use the mandatory
     * attribute addressStreet and submit the streetname and housenumber together â€“ alternatively
     * addressHouse + addressStreet can be used. For many international addresses there is no house
     * number, please do not set a period or any other sign to indicate that the address does not
     * have a housenumber.
     */
    public function setReturnAddress(ContactAddress $returnAddress): self
    {
        $this->returnAddress = Some::create($returnAddress);

        return $this;
    }

    /**
     * GoGreen Plus enables sustainable shipping by investing in measures to reduce greenhouse gas
     * emissions at DHL.
     */
    public function setGoGreenPlus(bool $goGreenPlus): self
    {
        $this->goGreenPlus = Some::create($goGreenPlus);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): VASDhlRetoure
    {
        return new VASDhlRetoure(
            $this->billingNumber,
            $this->refNo,
            $this->returnAddress,
            $this->goGreenPlus,
            $this->additionalProperties,
        );
    }
}
