<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use DateTimeInterface;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

/**
 * Builds a {@see VASIdentCheck}.
 */
final class VASIdentCheckBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<DateTimeInterface>                                $dateOfBirth
     * @param Option<VASIdentCheckMinimumAge|UnknownEnumValue<string>> $minimumAge
     * @param array<int|string, mixed>                                 $additionalProperties
     */
    public function __construct(
        private string $firstName,
        private string $lastName,
        private Option $dateOfBirth,
        private Option $minimumAge,
        private array $additionalProperties,
    ) {
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * date of birth, used in conjunction with minimumAge and shipping date. Format yyyy-mm-dd is
     * used.
     */
    public function setDateOfBirth(DateTimeInterface $dateOfBirth): self
    {
        $this->dateOfBirth = Some::create($dateOfBirth);

        return $this;
    }

    /**
     * Checks if recipient will have reached specified age by shipping date.
     */
    public function setMinimumAge(VASIdentCheckMinimumAge $minimumAge): self
    {
        $this->minimumAge = Some::create($minimumAge);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): VASIdentCheck
    {
        return new VASIdentCheck(
            $this->firstName,
            $this->lastName,
            $this->dateOfBirth,
            $this->minimumAge,
            $this->additionalProperties,
        );
    }
}
