<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Model;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_float;
use function is_int;
use function is_string;
use function sprintf;

final readonly class Weight implements SelfNormalizingModel
{
    /**
     * @param WeightUom|UnknownEnumValue<string> $uom
     * @param array<int|string, mixed>           $additionalProperties
     */
    public function __construct(
        private WeightUom|UnknownEnumValue $uom,
        private float $value,
        private array $additionalProperties,
    ) {
    }

    public static function builder(WeightUom $uom, float $value): WeightBuilder
    {
        return new WeightBuilder($uom, $value, []);
    }

    /**
     * metric unit for weight.
     *
     * @return WeightUom|UnknownEnumValue<string>
     */
    public function getUom(): WeightUom|UnknownEnumValue
    {
        return $this->uom;
    }

    public function getValue(): float
    {
        return $this->value;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $uom = null;
        $value = null;
        if (array_key_exists('value', $data) && is_int($data['value'])) {
            $data['value'] = (float) $data['value'];
        }
        if (array_key_exists('uom', $data)) {
            $uomRaw = $data['uom'];
            if (!is_string($uomRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "uom" must be string, got %s.', get_debug_type($uomRaw)),
                );
            }
            $uom = WeightUom::tryFrom($uomRaw) ?? UnknownEnumValue::of($uomRaw);
        }
        if (array_key_exists('value', $data)) {
            $valueRaw = $data['value'];
            if (!(is_float($valueRaw) || is_int($valueRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "value" must be number, got %s.', get_debug_type($valueRaw)),
                );
            }
            $value = (float) $valueRaw;
        }
        $additionalProperties = array_diff_key($data, ['uom' => true, 'value' => true]);
        if ($uom === null) {
            throw new MalformedDataException('Required property "uom" is missing from the document.');
        }
        if ($value === null) {
            throw new MalformedDataException('Required property "value" is missing from the document.');
        }

        return new self($uom, $value, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['uom'] = $this->uom->value;
        $dataArray['value'] = $this->value;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): WeightBuilder
    {
        return new WeightBuilder($this->uom, $this->value, $this->additionalProperties);
    }
}
