<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Api;

use Prefabcortex\DhlParcelDeShippingV2\Client;
use Prefabcortex\DhlParcelDeShippingV2\Exception\ApiException;
use Prefabcortex\DhlParcelDeShippingV2\Exception\MalformedResponseException;
use Prefabcortex\DhlParcelDeShippingV2\Exception\ResponseValidationException;
use Prefabcortex\DhlParcelDeShippingV2\Exception\RootGetInternalServerErrorException;
use Prefabcortex\DhlParcelDeShippingV2\Exception\RootGetTooManyRequestsException;
use Prefabcortex\DhlParcelDeShippingV2\Exception\RootGetUnauthorizedException;
use Prefabcortex\DhlParcelDeShippingV2\Exception\TransportException;
use Prefabcortex\DhlParcelDeShippingV2\Exception\UnexpectedContentTypeException;
use Prefabcortex\DhlParcelDeShippingV2\Exception\UnexpectedStatusCodeException;
use Prefabcortex\DhlParcelDeShippingV2\Exception\UnsupportedValueException;
use Prefabcortex\DhlParcelDeShippingV2\Model\ServiceInformation;
use Prefabcortex\DhlParcelDeShippingV2\Operation\General\RootGet;
use Psr\Http\Message\ResponseInterface;

/**
 * Get API version info.
 */
final readonly class GeneralApi
{
    public function __construct(private Client $client)
    {
    }

    /**
     * @throws ApiException
     * @throws UnsupportedValueException
     * @throws TransportException
     * @throws ResponseValidationException
     * @throws MalformedResponseException
     * @throws RootGetUnauthorizedException
     * @throws RootGetTooManyRequestsException
     * @throws RootGetInternalServerErrorException
     * @throws UnexpectedContentTypeException
     * @throws UnexpectedStatusCodeException
     */
    public function rootGet(): ServiceInformation
    {
        return $this->client->executeOperation(new RootGet());
    }

    /**
     * @throws ApiException
     * @throws UnsupportedValueException
     * @throws TransportException
     */
    public function rootGetRaw(): ResponseInterface
    {
        return $this->client->executeRawOperation(new RootGet());
    }
}
