<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Do not edit by hand: the next generation replaces this file. Changes belong in the
 * API description or in the generator.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Exception;

use InvalidArgumentException;

/**
 * A value handed to the package that it cannot put on the wire.
 *
 * Four places ask this question and all four ask it before a request is sent: the base URI that
 * names no scheme and no host and could therefore address no server, a query parameter holding
 * something with no query-string form, a multipart field holding something that is not a form part,
 * and an API key that no cookie value can carry. They differ in when the caller supplied the value,
 * not in what went wrong with it — so they are one type, and a consumer who wants to tell them
 * apart reads the message rather than catching another class.
 *
 * Extends `InvalidArgumentException` rather than replacing it. That is the type the first three
 * sites threw before, the type every published `@throws` named, and the type a consumer's existing
 * `catch` is written against; a subclass keeps all of them correct and adds the marker. Note the
 * root is load-bearing and not interchangeable with the one {@see MalformedDataException} uses:
 * `InvalidArgumentException` descends from `LogicException` and `UnexpectedValueException` from
 * `RuntimeException`, so the two live in disjoint halves of the SPL tree and moving a site across
 * would silently stop matching the catch written for it.
 *
 * That split is also the honest line between the two. This one says the caller passed something
 * wrong — knowable before anything is sent, fixable in their code. `MalformedDataException` says a
 * document was not what its description promised, which is only knowable once it arrives.
 *
 * It is an {@see ApiException} and not a `ResponseException` for the same reason {@see
 * NoHttpClientException} is not: nothing has been sent, so there is no response to hand back.
 */
final class UnsupportedValueException extends InvalidArgumentException implements ApiException
{
}
