<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Do not edit by hand: the next generation replaces this file. Changes belong in the
 * API description or in the generator.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Parameter;

use Prefabcortex\DhlParcelDeShippingV2\Http\QueryParameter;
use Prefabcortex\DhlParcelDeShippingV2\Http\QueryParameters;
use Prefabcortex\DhlParcelDeShippingV2\Http\ScalarValue;
use Prefabcortex\DhlParcelDeShippingV2\Model\GetManifestsIncludeDocs;
use Prefabcortex\DhlParcelDeShippingV2\Optional\None;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

final class GetManifestsQueryParameters
{
    /**
     * Customer billingNumber number.
     *
     * @var Option<string>
     */
    private Option $billingNumber;
    /** @var Option<string> */
    private Option $date;
    /**
     * Legacy name **labelResponseType**. Shipping labels and further shipment documents can be:
     * * __include__: included as base64 encoded data in the response (default)
     * * __URL__: provided as URL reference. Default is include the base64 encoded labels.
     *
     * @var Option<GetManifestsIncludeDocs>
     */
    private Option $includeDocs;

    public function __construct()
    {
        $this->billingNumber = None::create();
        $this->date = None::create();
        $this->includeDocs = None::create();
    }

    /** @return Option<string> */
    public function getBillingNumber(): Option
    {
        return $this->billingNumber;
    }

    public function withBillingNumber(string $billingNumber): self
    {
        $copy = clone $this;
        $copy->billingNumber = Some::create($billingNumber);

        return $copy;
    }

    /** @return Option<string> */
    public function getDate(): Option
    {
        return $this->date;
    }

    public function withDate(string $date): self
    {
        $copy = clone $this;
        $copy->date = Some::create($date);

        return $copy;
    }

    public function getIncludeDocs(): GetManifestsIncludeDocs
    {
        return $this->includeDocs->getOrElse(GetManifestsIncludeDocs::include);
    }

    public function withIncludeDocs(GetManifestsIncludeDocs $includeDocs): self
    {
        $copy = clone $this;
        $copy->includeDocs = Some::create($includeDocs);

        return $copy;
    }

    /**
     * @internal called by the generated operation, not part of this package's public
     *                  contract: it may change in any release
     */
    public function toQueryParameters(): QueryParameters
    {
        $parameters = [];
        if ($this->billingNumber->isDefined()) {
            $parameters[] = new QueryParameter('billingNumber', new ScalarValue($this->billingNumber->get()), false);
        }
        if ($this->date->isDefined()) {
            $parameters[] = new QueryParameter('date', new ScalarValue($this->date->get()), false);
        }
        if ($this->includeDocs->isDefined()) {
            $parameters[] = new QueryParameter('includeDocs', new ScalarValue($this->includeDocs->get()->value), false);
        }

        return new QueryParameters(...$parameters);
    }
}
