<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Do not edit by hand: the next generation replaces this file. Changes belong in the
 * API description or in the generator.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Parameter;

use Prefabcortex\DhlParcelDeShippingV2\Http\QueryParameter;
use Prefabcortex\DhlParcelDeShippingV2\Http\QueryParameters;
use Prefabcortex\DhlParcelDeShippingV2\Http\ScalarValue;
use Prefabcortex\DhlParcelDeShippingV2\Optional\None;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

final class ManifestsPostQueryParameters
{
    /**
     * Specify if all applicable shipments shall be marked as being ready for shipping.
     *
     * @var Option<bool>
     */
    private Option $all;

    public function __construct()
    {
        $this->all = None::create();
    }

    public function getAll(): bool
    {
        return $this->all->getOrElse(false);
    }

    public function withAll(bool $all): self
    {
        $copy = clone $this;
        $copy->all = Some::create($all);

        return $copy;
    }

    /**
     * @internal called by the generated operation, not part of this package's public
     *                  contract: it may change in any release
     */
    public function toQueryParameters(): QueryParameters
    {
        $parameters = [];
        if ($this->all->isDefined()) {
            $parameters[] = new QueryParameter('all', new ScalarValue($this->all->get()), false);
        }

        return new QueryParameters(...$parameters);
    }
}
