<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Parameter;

use Prefabcortex\DhlParcelDeShippingV2\Http\QueryParameter;
use Prefabcortex\DhlParcelDeShippingV2\Http\QueryParameters;
use Prefabcortex\DhlParcelDeShippingV2\Http\ScalarValue;

final readonly class OrdersAccountDeleteQueryParameters
{
    /**
     * @param string $profile  Defines the user group profile. A user group is permitted to specific
     *                         billing numbers. Shipments are only canceled if they belong to a
     *                         billing number that the user group profile is entitled to use. This
     *                         attribute is mandatory. Please use the standard user group profile
     *                         'STANDARD_GRUPPENPROFIL' if no dedicated user group profile is
     *                         available.
     * @param string $shipment Shipment number that shall be canceled. If multiple shipments shall
     *                         be canceled, the parameter must be added multiple times. Up to 30
     *                         shipments can be canceled at once.
     */
    public function __construct(private string $profile, private string $shipment)
    {
    }

    public function getProfile(): string
    {
        return $this->profile;
    }

    public function getShipment(): string
    {
        return $this->shipment;
    }

    /**
     * @internal called by the generated operation, not part of this package's public
     *                  contract: it may change in any release
     */
    public function toQueryParameters(): QueryParameters
    {
        $parameters = [];
        $parameters[] = new QueryParameter('profile', new ScalarValue($this->profile), false);
        $parameters[] = new QueryParameter('shipment', new ScalarValue($this->shipment), false);

        return new QueryParameters(...$parameters);
    }
}
