<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Do not edit by hand: the next generation replaces this file. Changes belong in the
 * API description or in the generator.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Parameter;

use Prefabcortex\DhlParcelDeShippingV2\Http\HeaderParameter;
use Prefabcortex\DhlParcelDeShippingV2\Http\HeaderParameters;
use Prefabcortex\DhlParcelDeShippingV2\Http\ScalarValue;
use Prefabcortex\DhlParcelDeShippingV2\Optional\None;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Option;
use Prefabcortex\DhlParcelDeShippingV2\Optional\Some;

final class OrdersAccountDeleteHeaderParameters
{
    /**
     * Control the APIs response language via locale abbreviation. English (en-US) and german
     * (de-DE) are supported. If not specified, the default is english.
     *
     * @var Option<string>
     */
    private Option $acceptLanguage;

    public function __construct()
    {
        $this->acceptLanguage = None::create();
    }

    /** @return Option<string> */
    public function getAcceptLanguage(): Option
    {
        return $this->acceptLanguage;
    }

    public function setAcceptLanguage(string $acceptLanguage): self
    {
        $this->acceptLanguage = Some::create($acceptLanguage);

        return $this;
    }

    /**
     * @internal called by the generated operation, not part of this package's public
     *                  contract: it may change in any release
     */
    public function toHeaderParameters(): HeaderParameters
    {
        $parameters = [];
        if ($this->acceptLanguage->isDefined()) {
            $parameters[] = new HeaderParameter('Accept-Language', new ScalarValue($this->acceptLanguage->get()));
        }

        return new HeaderParameters(...$parameters);
    }
}
