<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Validator;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Model\ServiceInformationAmp;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ServiceInformationAmp} has to satisfy.
 */
final class ServiceInformationAmpConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'name' => new Optional([new Type(['string']), new NotNull()]),
                'env' => new Optional([new Type(['string']), new NotNull()]),
                'version' => new Optional([new Type(['string']), new NotNull()]),
                'rev' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
