<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Do not edit by hand: the next generation replaces this file. Changes belong in the
 * API description or in the generator.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Validator;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Model\ShipmentNoToSheetNo;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ShipmentNoToSheetNo} has to satisfy.
 */
final class ShipmentNoToSheetNoConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'shipmentNo' => new Optional([new Type(['string']), new NotNull()]),
                'sheetNo' => new Optional([new Type(['string']), new NotNull()]),
                'sstatus' => new Optional([new NotNull(), ...RequestStatusConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
