<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Do not edit by hand: the next generation replaces this file. Changes belong in the
 * API description or in the generator.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Validator;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Model\SingleManifestResponse;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * @see SingleManifestResponse
 *
 * @internal validation rules for the model above, not part of this package's public
 *                      contract: they may change in any release
 */
final class SingleManifestResponseConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'status' => new Optional([new NotNull(), ...RequestStatusConstraint::constraints()]),
                'manifestDate' => new Optional([new Type(['string']), new NotNull()]),
                'manifest' => new Optional([new All([...DocumentConstraint::constraints()]), new Type(['array']), new NotNull()]),
                'sheetNo' => new Optional([new All([...BillingNoToSheetNoConstraint::constraints()]), new Type(['array']), new NotNull()]),
                'items' => new Optional([new All([...ShipmentNoToSheetNoConstraint::constraints()]), new Type(['array']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
