<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Do not edit by hand: the next generation replaces this file. Changes belong in the
 * API description or in the generator.
 */
declare(strict_types=1);

namespace Prefabcortex\DhlParcelDeShippingV2\Validator;

use Override;
use Prefabcortex\DhlParcelDeShippingV2\Model\Weight;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;
use Symfony\Component\Validator\Constraints\LessThanOrEqual;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see Weight} has to satisfy.
 */
final class WeightConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'uom' => new Required([...WeightUomConstraint::constraints()]),
                'value' => new Required([
                    new LessThanOrEqual(31500.0),
                    new GreaterThanOrEqual(0.0),
                    new Type(['number']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
